spring:
  thymeleaf:
    # 关闭缓存
    cache: false
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://106.55.17.104:3306/core?characterEncoding=utf-8&encrypted=0
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认600000（十分钟）
      idle-timeout: 1800000
      # 最大连接数 默认10
      maximum-pool-size: 10
      # 最大存活时间 0表示永久存活，默认1800000（半小时）
      max-lifetime: 1800000
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接超时时间
      connection-timeout: 30000
      # 连接心跳测试语句
      connection-test-query: SELECT 1


#mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类别名（默认是类名）
  type-aliases-package:  com.satella.seckill.pojo

# Mybatis SQL大英（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.satella.seckill.mapper: debug